apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ (index .Values.namespace .Values.profile) }}
  annotations:
    "meta.helm.sh/release-name": {{ $.Chart.Name | quote }}
    "meta.helm.sh/release-namespace":
      {{ index .Values.namespace .Values.profile | quote }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/managed-by: "Helm"
spec:
  type: NodePort
  ports:
    - name: restful 
      port: {{ (index .Values.configs .Values.profile).PortRestful }}
      protocol: TCP
      targetPort: {{ (index .Values.configs .Values.profile).PortRestful }}
    - name: grpc
      port: {{ (index .Values.configs .Values.profile).Port }}
      protocol: TCP
      targetPort: {{ (index .Values.configs .Values.profile).Port }}
  selector:
    app: {{ .Values.name }}
