package constant_v1

const (
	REDEMPTION_TYPE_CASH = "CASH"
	REDEMPTION_TYPE_UNIT = "UNIT"
	REDEMPTION_TYPE_MIX  = "MIX"

	DISPLAY_REDEMPTION_TYPE_AMT  = "AMT"
	DISPLAY_REDEMPTION_TYPE_UNIT = "UNIT"
	DISPLAY_REDEMPTION_TYPE_MIX  = "MIX"
)

var (
	REDEMPTION_TYPE_METHOD = map[string]string{
		REDEMPTION_TYPE_CASH: DISPLAY_REDEMPTION_TYPE_AMT,
		REDEMPTION_TYPE_UNIT: DISPLAY_REDEMPTION_TYPE_UNIT,
		REDEMPTION_TYPE_MIX:  DISPLAY_REDEMPTION_TYPE_MIX,
	}
)
